In [1]:
# Part 1 - Data Preprocessing
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [75]:
# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')
# Select what variables to include for prediction
X = dataset.iloc[:,3:13].values
y = dataset.iloc[:,13].values
#to test a new var, we create a test vector, append at the end
test_vec = np.array([[600, 'France', 'Male', 40, 3, 60000, 2, 1, 1, 50000]])
print(X.shape, test_vec.shape)
X = np.concatenate([X, test_vec])
len(X)
X[10000]

((10000, 10), (1, 10))


array(['600', 'France', 'Male', '40', '3', '60000', '2', '1', '1',
       '50000'], dtype=object)

In [76]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])


In [77]:
#remove one of the country, avoid the dummy variable trap
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]
X[:3]

array([[0.0000000e+00, 0.0000000e+00, 6.1900000e+02, 0.0000000e+00,
        4.2000000e+01, 2.0000000e+00, 0.0000000e+00, 1.0000000e+00,
        1.0000000e+00, 1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 1.0000000e+00, 6.0800000e+02, 0.0000000e+00,
        4.1000000e+01, 1.0000000e+00, 8.3807860e+04, 1.0000000e+00,
        0.0000000e+00, 1.0000000e+00, 1.1254258e+05],
       [0.0000000e+00, 0.0000000e+00, 5.0200000e+02, 0.0000000e+00,
        4.2000000e+01, 8.0000000e+00, 1.5966080e+05, 3.0000000e+00,
        1.0000000e+00, 0.0000000e+00, 1.1393157e+05]])

In [94]:
test_vec = X[10000:,]
test_vec.shape

(1, 11)

In [5]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [6]:
len(X_train)

8000

In [7]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [8]:
X_train

array([[-0.5698444 ,  1.74309049,  0.16958176, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [ 1.75486502, -0.57369368, -2.30455945, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [-0.5698444 , -0.57369368, -1.19119591, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [-0.5698444 , -0.57369368,  0.9015152 , ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-0.5698444 ,  1.74309049, -0.62420521, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [ 1.75486502, -0.57369368, -0.28401079, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [9]:
# Part 2 - Now let's make the ANN!

# Importing the Keras libraries and packages
import keras

Using TensorFlow backend.


In [11]:
from keras.models import Sequential
from keras.layers import Dense

In [12]:
# Initialising the ANN
classifier = Sequential()

In [13]:
# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

In [14]:
# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

In [15]:
# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

In [16]:
# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [17]:
# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
8000/8000 [==============================] - 4s 459us/step - loss: 0.4809 - acc: 0.7950
Epoch 2/100
8000/8000 [==============================] - 3s 404us/step - loss: 0.4280 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 3s 387us/step - loss: 0.4221 - acc: 0.7962
Epoch 4/100
8000/8000 [==============================] - 3s 422us/step - loss: 0.4181 - acc: 0.8227
Epoch 5/100
8000/8000 [==============================] - 4s 493us/step - loss: 0.4155 - acc: 0.8271
Epoch 6/100
8000/8000 [==============================] - 11s 1ms/step - loss: 0.4140 - acc: 0.8290
Epoch 7/100
8000/8000 [==============================] - 16s 2ms/step - loss: 0.4126 - acc: 0.8322
Epoch 8/100
8000/8000 [==============================] - 5s 585us/step - loss: 0.4109 - acc: 0.8334
Epoch 9/100
8000/8000 [==============================] - 4s 494us/step - loss: 0.4105 - acc: 0.8327
Epoch 10/100
8000/8000 [==============================] - 4s 480us/step - loss: 0.4097 - acc: 0.8344
E

In [102]:
# Part 3 - Making predictions and evaluating the model

# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

#prediction for test_vect
y_pred_test = classifier.predict(test_vec)
#y_pred_test = (y_pred_test > 0.5)
y_pred_test[0,0]

0.0

In [19]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [20]:
cm

array([[1541,   54],
       [ 257,  148]])

In [21]:
(1541 + 257)/20

89

In [24]:
dataset.columns

Index([u'RowNumber', u'CustomerId', u'Surname', u'CreditScore', u'Geography',
       u'Gender', u'Age', u'Tenure', u'Balance', u'NumOfProducts',
       u'HasCrCard', u'IsActiveMember', u'EstimatedSalary', u'Exited'],
      dtype='object')

In [27]:
dataset.values[0:2]

array([[1, 15634602, 'Hargrave', 619, 'France', 'Female', 42, 2, 0.0, 1,
        1, 1, 101348.88, 1],
       [2, 15647311, 'Hill', 608, 'Spain', 'Female', 41, 1, 83807.86, 1,
        0, 1, 112542.58, 0]], dtype=object)

In [28]:
X[0:2]

array([[0.0000000e+00, 0.0000000e+00, 6.1900000e+02, 0.0000000e+00,
        4.2000000e+01, 2.0000000e+00, 0.0000000e+00, 1.0000000e+00,
        1.0000000e+00, 1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 1.0000000e+00, 6.0800000e+02, 0.0000000e+00,
        4.1000000e+01, 1.0000000e+00, 8.3807860e+04, 1.0000000e+00,
        0.0000000e+00, 1.0000000e+00, 1.1254258e+05]])