In [1]:
# Part 1 - Data Preprocessing
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')
# Select what variables to include for prediction
X = dataset.iloc[:,3:13].values
y = dataset.iloc[:,13].values
#to test a new var, we create a test vector, append at the end
#test_vec = np.array([[600, 'France', 'Male', 40, 3, 60000, 2, 1, 1, 50000]])
#print(X.shape, test_vec.shape)
#X = np.concatenate([X, test_vec])
#len(X)
#X[10000]

In [3]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])


In [4]:
#remove one of the country, avoid the dummy variable trap
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]
X[:3]

/mnt/c/Users/kkart/Desktop/Work/MOOCS/DLA2Z/DLA2Z/local/lib/python2.7/site-packages/sklearn/preprocessing/_encoders.py:363: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/mnt/c/Users/kkart/Desktop/Work/MOOCS/DLA2Z/DLA2Z/local/lib/python2.7/site-packages/sklearn/preprocessing/_encoders.py:385: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


array([[0.0000000e+00, 0.0000000e+00, 6.1900000e+02, 0.0000000e+00,
        4.2000000e+01, 2.0000000e+00, 0.0000000e+00, 1.0000000e+00,
        1.0000000e+00, 1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 1.0000000e+00, 6.0800000e+02, 0.0000000e+00,
        4.1000000e+01, 1.0000000e+00, 8.3807860e+04, 1.0000000e+00,
        0.0000000e+00, 1.0000000e+00, 1.1254258e+05],
       [0.0000000e+00, 0.0000000e+00, 5.0200000e+02, 0.0000000e+00,
        4.2000000e+01, 8.0000000e+00, 1.5966080e+05, 3.0000000e+00,
        1.0000000e+00, 0.0000000e+00, 1.1393157e+05]])

In [5]:
test_vec = X[10000:,]
test_vec.shape

(0, 11)

In [6]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [7]:
len(X_train)

8000

In [8]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [9]:
X_train

array([[-0.5698444 ,  1.74309049,  0.16958176, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [ 1.75486502, -0.57369368, -2.30455945, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [-0.5698444 , -0.57369368, -1.19119591, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [-0.5698444 , -0.57369368,  0.9015152 , ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-0.5698444 ,  1.74309049, -0.62420521, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [ 1.75486502, -0.57369368, -0.28401079, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [10]:
# Part 2 - Now let's make the ANN!

# Importing the Keras libraries and packages
import keras

Using TensorFlow backend.


In [11]:
from keras.models import Sequential
from keras.layers import Dense

In [12]:
# Initialising the ANN
classifier = Sequential()

In [13]:
# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

In [14]:
# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

In [15]:
# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

In [16]:
# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [17]:
# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100);

Epoch 1/100
8000/8000 [==============================] - 1s 142us/step - loss: 0.4804 - acc: 0.7955
Epoch 2/100
8000/8000 [==============================] - 1s 97us/step - loss: 0.4270 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 97us/step - loss: 0.4219 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 103us/step - loss: 0.4184 - acc: 0.8211
Epoch 5/100
8000/8000 [==============================] - 1s 122us/step - loss: 0.4161 - acc: 0.8269
Epoch 6/100
8000/8000 [==============================] - 1s 111us/step - loss: 0.4144 - acc: 0.8279
Epoch 7/100
8000/8000 [==============================] - 1s 128us/step - loss: 0.4124 - acc: 0.8307
Epoch 8/100
8000/8000 [==============================] - 1s 107us/step - loss: 0.4117 - acc: 0.8320
Epoch 9/100
8000/8000 [==============================] - 1s 115us/step - loss: 0.4106 - acc: 0.8331
Epoch 10/100
8000/8000 [==============================] - 1s 114us/step - loss: 0.4097 - acc: 0.8339
E

8000/8000 [==============================] - 1s 84us/step - loss: 0.4000 - acc: 0.8345
Epoch 83/100
8000/8000 [==============================] - 1s 93us/step - loss: 0.4002 - acc: 0.8356
Epoch 84/100
8000/8000 [==============================] - 1s 87us/step - loss: 0.4000 - acc: 0.8356
Epoch 85/100
8000/8000 [==============================] - 1s 88us/step - loss: 0.3995 - acc: 0.8344
Epoch 86/100
8000/8000 [==============================] - 1s 88us/step - loss: 0.3998 - acc: 0.8349
Epoch 87/100
8000/8000 [==============================] - 1s 90us/step - loss: 0.4002 - acc: 0.8346
Epoch 88/100
8000/8000 [==============================] - 1s 91us/step - loss: 0.4002 - acc: 0.8349
Epoch 89/100
8000/8000 [==============================] - 1s 87us/step - loss: 0.3994 - acc: 0.8352
Epoch 90/100
8000/8000 [==============================] - 1s 90us/step - loss: 0.3999 - acc: 0.8366
Epoch 91/100
8000/8000 [==============================] - 1s 92us/step - loss: 0.4000 - acc: 0.8352
Epoch 92/100


In [19]:
# Part 3 - Making predictions and evaluating the model

# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

#prediction for test_vect
y_pred_test = classifier.predict(test_vec)
y_pred_test = (y_pred_test > 0.5)
#y_pred_test[0,0]

In [20]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [21]:
cm

array([[1543,   52],
       [ 261,  144]])

In [22]:
(1541 + 257)/20

89

In [23]:
dataset.columns

Index([u'RowNumber', u'CustomerId', u'Surname', u'CreditScore', u'Geography',
       u'Gender', u'Age', u'Tenure', u'Balance', u'NumOfProducts',
       u'HasCrCard', u'IsActiveMember', u'EstimatedSalary', u'Exited'],
      dtype='object')

In [24]:
dataset.values[0:2]

array([[1, 15634602, 'Hargrave', 619, 'France', 'Female', 42, 2, 0.0, 1,
        1, 1, 101348.88, 1],
       [2, 15647311, 'Hill', 608, 'Spain', 'Female', 41, 1, 83807.86, 1,
        0, 1, 112542.58, 0]], dtype=object)

In [25]:
X[0:2]

array([[0.0000000e+00, 0.0000000e+00, 6.1900000e+02, 0.0000000e+00,
        4.2000000e+01, 2.0000000e+00, 0.0000000e+00, 1.0000000e+00,
        1.0000000e+00, 1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 1.0000000e+00, 6.0800000e+02, 0.0000000e+00,
        4.1000000e+01, 1.0000000e+00, 8.3807860e+04, 1.0000000e+00,
        0.0000000e+00, 1.0000000e+00, 1.1254258e+05]])

## Implement cross-validation

In [27]:
#need to import keras wrapper for scikitlearn 
from keras.wrappers.scikit_learn import KerasClassifier

In [35]:
from sklearn.model_selection import cross_val_score
from keras.models import Sequential
from keras.layers import Dense

In [36]:
#define a function to build the classifier layer by layer

def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier;

In [40]:
Classifier = KerasClassifier(build_fn=build_classifier, batch_size = 10, epochs = 100);
#importance of batch_size while training, trains faster, less memory but what about weights.
#the learning rate is affected -> batch, mini_batch (size < set), stochastic(size = 1)

In [44]:
accuracies = cross_val_score(estimator= Classifier,X = X_train,y = y_train, cv=10);#,n_jobs=1);

Epoch 1/100
7200/7200 [==============================] - 2s 283us/step - loss: 0.5024 - acc: 0.7968
Epoch 2/100
7200/7200 [==============================] - 1s 193us/step - loss: 0.4294 - acc: 0.7971
Epoch 3/100
7200/7200 [==============================] - 1s 188us/step - loss: 0.4237 - acc: 0.8022
Epoch 4/100
7200/7200 [==============================] - 1s 189us/step - loss: 0.4181 - acc: 0.8235
Epoch 5/100
7200/7200 [==============================] - 1s 193us/step - loss: 0.4131 - acc: 0.8311
Epoch 6/100
7200/7200 [==============================] - 1s 193us/step - loss: 0.4096 - acc: 0.8312 0s - loss: 0.4088 - acc: 0.83
Epoch 7/100
7200/7200 [==============================] - 1s 204us/step - loss: 0.4069 - acc: 0.8337
Epoch 8/100
7200/7200 [==============================] - 2s 216us/step - loss: 0.4049 - acc: 0.8346 0s - loss: 0.4093 - acc: 
Epoch 9/100
7200/7200 [==============================] - 1s 195us/step - loss: 0.4030 - acc: 0.8349
Epoch 10/100
7200/7200 [====================

7200/7200 [==============================] - 1s 176us/step - loss: 0.3420 - acc: 0.8593
Epoch 81/100
7200/7200 [==============================] - 1s 176us/step - loss: 0.3417 - acc: 0.8579 0s - loss: 0.3553 
Epoch 82/100
7200/7200 [==============================] - 1s 175us/step - loss: 0.3405 - acc: 0.8615
Epoch 83/100
7200/7200 [==============================] - 1s 174us/step - loss: 0.3422 - acc: 0.8597
Epoch 84/100
7200/7200 [==============================] - 1s 175us/step - loss: 0.3398 - acc: 0.8592
Epoch 85/100
7200/7200 [==============================] - 1s 173us/step - loss: 0.3412 - acc: 0.8607
Epoch 86/100
7200/7200 [==============================] - 1s 178us/step - loss: 0.3405 - acc: 0.8593
Epoch 87/100
7200/7200 [==============================] - 1s 176us/step - loss: 0.3402 - acc: 0.8589
Epoch 88/100
7200/7200 [==============================] - 1s 176us/step - loss: 0.3407 - acc: 0.8603 1s - los
Epoch 89/100
7200/7200 [==============================] - 1s 175us/step - lo

7200/7200 [==============================] - 1s 179us/step - loss: 0.3403 - acc: 0.8604
Epoch 60/100
7200/7200 [==============================] - 1s 177us/step - loss: 0.3392 - acc: 0.8622
Epoch 61/100
7200/7200 [==============================] - 1s 171us/step - loss: 0.3397 - acc: 0.8601
Epoch 62/100
7200/7200 [==============================] - 1s 154us/step - loss: 0.3387 - acc: 0.8617
Epoch 63/100
7200/7200 [==============================] - 1s 175us/step - loss: 0.3393 - acc: 0.8607
Epoch 64/100
7200/7200 [==============================] - 1s 179us/step - loss: 0.3383 - acc: 0.8631
Epoch 65/100
7200/7200 [==============================] - 1s 177us/step - loss: 0.3387 - acc: 0.8626
Epoch 66/100
7200/7200 [==============================] - 1s 177us/step - loss: 0.3391 - acc: 0.8601
Epoch 67/100
7200/7200 [==============================] - 1s 177us/step - loss: 0.3397 - acc: 0.8601
Epoch 68/100
7200/7200 [==============================] - 1s 177us/step - loss: 0.3392 - acc: 0.8592
Epo

7200/7200 [==============================] - 1s 207us/step - loss: 0.4032 - acc: 0.8356
Epoch 40/100
7200/7200 [==============================] - 1s 180us/step - loss: 0.4029 - acc: 0.8356
Epoch 41/100
7200/7200 [==============================] - 1s 186us/step - loss: 0.4030 - acc: 0.8353
Epoch 42/100
7200/7200 [==============================] - 1s 174us/step - loss: 0.4023 - acc: 0.8340
Epoch 43/100
7200/7200 [==============================] - 1s 182us/step - loss: 0.4025 - acc: 0.8347
Epoch 44/100
7200/7200 [==============================] - 1s 190us/step - loss: 0.4022 - acc: 0.8347
Epoch 45/100
7200/7200 [==============================] - 1s 204us/step - loss: 0.4023 - acc: 0.8368
Epoch 46/100
7200/7200 [==============================] - 1s 193us/step - loss: 0.4023 - acc: 0.8346
Epoch 47/100
7200/7200 [==============================] - 1s 189us/step - loss: 0.4026 - acc: 0.8339
Epoch 48/100
7200/7200 [==============================] - 1s 185us/step - loss: 0.4021 - acc: 0.8339
Epo

7200/7200 [==============================] - 1s 182us/step - loss: 0.4041 - acc: 0.8358
Epoch 18/100
7200/7200 [==============================] - 1s 183us/step - loss: 0.4034 - acc: 0.8356
Epoch 19/100
7200/7200 [==============================] - 1s 184us/step - loss: 0.4032 - acc: 0.8367
Epoch 20/100
7200/7200 [==============================] - 1s 182us/step - loss: 0.4030 - acc: 0.8344
Epoch 21/100
7200/7200 [==============================] - 1s 184us/step - loss: 0.4025 - acc: 0.8367
Epoch 22/100
7200/7200 [==============================] - 1s 183us/step - loss: 0.4019 - acc: 0.8354
Epoch 23/100
7200/7200 [==============================] - 1s 187us/step - loss: 0.4022 - acc: 0.8374 0s - loss: 0.39
Epoch 24/100
7200/7200 [==============================] - 1s 185us/step - loss: 0.4014 - acc: 0.8350
Epoch 25/100
7200/7200 [==============================] - 1s 188us/step - loss: 0.4015 - acc: 0.8357
Epoch 26/100
7200/7200 [==============================] - 1s 184us/step - loss: 0.4011 -

7200/7200 [==============================] - 1s 184us/step - loss: 0.3980 - acc: 0.8339
Epoch 95/100
7200/7200 [==============================] - 1s 184us/step - loss: 0.3979 - acc: 0.8376
Epoch 96/100
7200/7200 [==============================] - 1s 185us/step - loss: 0.3975 - acc: 0.8357
Epoch 97/100
7200/7200 [==============================] - 1s 183us/step - loss: 0.3977 - acc: 0.8347
Epoch 98/100
7200/7200 [==============================] - 1s 183us/step - loss: 0.3975 - acc: 0.8351
Epoch 99/100
7200/7200 [==============================] - 1s 182us/step - loss: 0.3975 - acc: 0.8364
Epoch 100/100
800/800 [==============================] - 0s 344us/step
Epoch 1/100
7200/7200 [==============================] - 2s 293us/step - loss: 0.4905 - acc: 0.7935
Epoch 2/100
7200/7200 [==============================] - 1s 186us/step - loss: 0.4322 - acc: 0.7937
Epoch 3/100
7200/7200 [==============================] - 1s 186us/step - loss: 0.4269 - acc: 0.7937
Epoch 4/100
7200/7200 [=============

7200/7200 [==============================] - 2s 226us/step - loss: 0.4037 - acc: 0.8343
Epoch 75/100
7200/7200 [==============================] - 2s 224us/step - loss: 0.4034 - acc: 0.8324
Epoch 76/100
7200/7200 [==============================] - 2s 259us/step - loss: 0.4038 - acc: 0.8344
Epoch 77/100
7200/7200 [==============================] - 2s 238us/step - loss: 0.4035 - acc: 0.8331
Epoch 78/100
7200/7200 [==============================] - 2s 224us/step - loss: 0.4037 - acc: 0.8339
Epoch 79/100
7200/7200 [==============================] - 2s 230us/step - loss: 0.4037 - acc: 0.8326
Epoch 80/100
7200/7200 [==============================] - 2s 229us/step - loss: 0.4035 - acc: 0.8324 0s - loss: 0.4005 -
Epoch 81/100
7200/7200 [==============================] - 2s 231us/step - loss: 0.4033 - acc: 0.8331
Epoch 82/100
7200/7200 [==============================] - 2s 266us/step - loss: 0.4027 - acc: 0.8343
Epoch 83/100
7200/7200 [==============================] - 2s 250us/step - loss: 0.40

Epoch 53/100
7200/7200 [==============================] - 1s 190us/step - loss: 0.3375 - acc: 0.8615
Epoch 54/100
7200/7200 [==============================] - 1s 188us/step - loss: 0.3395 - acc: 0.8622
Epoch 55/100
7200/7200 [==============================] - 1s 189us/step - loss: 0.3393 - acc: 0.8604
Epoch 56/100
7200/7200 [==============================] - 1s 188us/step - loss: 0.3390 - acc: 0.8614
Epoch 57/100
7200/7200 [==============================] - 1s 190us/step - loss: 0.3386 - acc: 0.8612
Epoch 58/100
7200/7200 [==============================] - 1s 191us/step - loss: 0.3390 - acc: 0.8604
Epoch 59/100
7200/7200 [==============================] - 1s 190us/step - loss: 0.3381 - acc: 0.8617
Epoch 60/100
7200/7200 [==============================] - 1s 191us/step - loss: 0.3395 - acc: 0.8604
Epoch 61/100
7200/7200 [==============================] - 1s 189us/step - loss: 0.3392 - acc: 0.8611
Epoch 62/100
7200/7200 [==============================] - 1s 158us/step - loss: 0.3389 - ac

7200/7200 [==============================] - 1s 191us/step - loss: 0.4037 - acc: 0.8353
Epoch 31/100
7200/7200 [==============================] - 1s 190us/step - loss: 0.4039 - acc: 0.8357
Epoch 32/100
7200/7200 [==============================] - 1s 191us/step - loss: 0.4034 - acc: 0.8349
Epoch 33/100
7200/7200 [==============================] - 1s 190us/step - loss: 0.4035 - acc: 0.8350
Epoch 34/100
7200/7200 [==============================] - 1s 190us/step - loss: 0.4030 - acc: 0.8356
Epoch 35/100
7200/7200 [==============================] - 1s 193us/step - loss: 0.4032 - acc: 0.8344
Epoch 36/100
7200/7200 [==============================] - 1s 193us/step - loss: 0.4026 - acc: 0.8342
Epoch 37/100
7200/7200 [==============================] - 1s 193us/step - loss: 0.4030 - acc: 0.8342
Epoch 38/100
7200/7200 [==============================] - 1s 193us/step - loss: 0.4030 - acc: 0.8354
Epoch 39/100
7200/7200 [==============================] - 1s 191us/step - loss: 0.4027 - acc: 0.8351
Epo

7200/7200 [==============================] - 1s 195us/step - loss: 0.4098 - acc: 0.8321
Epoch 10/100
7200/7200 [==============================] - 1s 201us/step - loss: 0.4087 - acc: 0.8346
Epoch 11/100
7200/7200 [==============================] - 2s 220us/step - loss: 0.4085 - acc: 0.8342
Epoch 12/100
7200/7200 [==============================] - 2s 212us/step - loss: 0.4071 - acc: 0.8343
Epoch 13/100
7200/7200 [==============================] - 2s 225us/step - loss: 0.4063 - acc: 0.8337
Epoch 14/100
7200/7200 [==============================] - 2s 223us/step - loss: 0.4060 - acc: 0.8349
Epoch 15/100
7200/7200 [==============================] - 2s 231us/step - loss: 0.4057 - acc: 0.8358
Epoch 16/100
7200/7200 [==============================] - 1s 193us/step - loss: 0.4041 - acc: 0.8347
Epoch 17/100
7200/7200 [==============================] - 1s 167us/step - loss: 0.4050 - acc: 0.8371
Epoch 18/100
7200/7200 [==============================] - 2s 228us/step - loss: 0.4046 - acc: 0.8346
Epo

Epoch 90/100
7200/7200 [==============================] - 1s 195us/step - loss: 0.3977 - acc: 0.8342
Epoch 91/100
7200/7200 [==============================] - 1s 195us/step - loss: 0.3978 - acc: 0.8358
Epoch 92/100
7200/7200 [==============================] - 1s 196us/step - loss: 0.3980 - acc: 0.8354
Epoch 93/100
7200/7200 [==============================] - 1s 197us/step - loss: 0.3976 - acc: 0.8356
Epoch 94/100
7200/7200 [==============================] - 1s 196us/step - loss: 0.3969 - acc: 0.8354 0s - loss: 0
Epoch 95/100
7200/7200 [==============================] - 1s 195us/step - loss: 0.3972 - acc: 0.8351
Epoch 96/100
7200/7200 [==============================] - 1s 196us/step - loss: 0.3978 - acc: 0.8360
Epoch 97/100
7200/7200 [==============================] - 1s 197us/step - loss: 0.3977 - acc: 0.8335
Epoch 98/100
7200/7200 [==============================] - 1s 198us/step - loss: 0.3977 - acc: 0.8354
Epoch 99/100
7200/7200 [==============================] - 1s 196us/step - loss

7200/7200 [==============================] - 2s 222us/step - loss: 0.3332 - acc: 0.8629
Epoch 69/100
7200/7200 [==============================] - 2s 239us/step - loss: 0.3342 - acc: 0.8621
Epoch 70/100
7200/7200 [==============================] - 2s 241us/step - loss: 0.3331 - acc: 0.8628 0s - loss: 0.3288
Epoch 71/100
7200/7200 [==============================] - 2s 240us/step - loss: 0.3340 - acc: 0.8653
Epoch 72/100
7200/7200 [==============================] - 2s 236us/step - loss: 0.3326 - acc: 0.8619
Epoch 73/100
7200/7200 [==============================] - 2s 236us/step - loss: 0.3337 - acc: 0.8617 0s - loss: 0.
Epoch 74/100
7200/7200 [==============================] - 2s 239us/step - loss: 0.3335 - acc: 0.8668
Epoch 75/100
7200/7200 [==============================] - 2s 228us/step - loss: 0.3324 - acc: 0.8612
Epoch 76/100
7200/7200 [==============================] - 2s 230us/step - loss: 0.3322 - acc: 0.8631
Epoch 77/100
7200/7200 [==============================] - 2s 226us/step 

7200/7200 [==============================] - 2s 209us/step - loss: 0.3358 - acc: 0.8633
Epoch 48/100
7200/7200 [==============================] - 1s 208us/step - loss: 0.3363 - acc: 0.8632
Epoch 49/100
7200/7200 [==============================] - 1s 206us/step - loss: 0.3359 - acc: 0.8639
Epoch 50/100
7200/7200 [==============================] - 1s 206us/step - loss: 0.3354 - acc: 0.8644
Epoch 51/100
7200/7200 [==============================] - 1s 207us/step - loss: 0.3360 - acc: 0.8632
Epoch 52/100
7200/7200 [==============================] - 1s 208us/step - loss: 0.3356 - acc: 0.8636
Epoch 53/100
7200/7200 [==============================] - 1s 205us/step - loss: 0.3351 - acc: 0.8647
Epoch 54/100
7200/7200 [==============================] - 2s 209us/step - loss: 0.3352 - acc: 0.8660
Epoch 55/100
7200/7200 [==============================] - 1s 208us/step - loss: 0.3346 - acc: 0.8646
Epoch 56/100
7200/7200 [==============================] - 1s 207us/step - loss: 0.3360 - acc: 0.8646
Epo

In [45]:
accuracies

array([0.85749999, 0.85499999, 0.83374999, 0.83125   , 0.84874999,
       0.8575    , 0.83125   , 0.82374999, 0.84124999, 0.8625    ])

In [46]:
mean = accuracies.mean()
var = accuracies.std()

In [47]:
mean, var

(0.8442499946430326, 0.013028814020360576)

#important to make a note of bias_variance tradeoff, as we want to have low bias, low variance-->ISLR notes
![Image of Bias_Var Tradeoff](https://www.google.co.in/url?sa=i&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwi4kp7-qtveAhVZWX0KHc30CqkQjRx6BAgBEAU&url=https%3A%2F%2Fwww.kdnuggets.com%2F2016%2F08%2Fbias-variance-tradeoff-overview.html&psig=AOvVaw0yWdVXvdBg7K0nqhE-SqrX&ust=1542540950141910) 

#### Now that we have trained and validated a model successfully, its time to improve the performace
### Parameter Tuning-